config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  resources :users do
    resources :courses, :students
  end
  resources :students do
    resources :courses
  end
  resources :courses do
    resources :lessons
  end
  resources :lessons
  resources :sessions, only: [:new, :create]
  get 'courses/by_student/:student_id/:user_id', to: 'courses#index'
  get '/signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get 'course/alpha', to: 'courses#alpha'
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :courses
    has_many :users, through: :courses
    has_many :lessons, through: :courses
    validates :name, :grade, presence: true
    validates :name, uniqueness: true
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def index
        if session[:user_id]
            @students = current_user.students.uniq.sort_by {|s| s.name}
        else
            flash[:alert] = "Must be signed in to view students."
            redirect_to signin_path
        end
    end
    
    def new
        if session[:user_id]
            @student = Student.new
        else
            flash[:alert] = "Must be logged in to create student."
            redirect_to signin_path
        end
    end
    
    def create
        @student = Student.new(student_params)
        if @student.save
            redirect_to user_path(current_user)
        else
            flash.now[:alert] = @student.errors.full_messages
            render :new
        end
    end
    
    def show
        @student = Student.find(params[:id])
    end

    def destroy
        student = Student.find(params[:id])
        student.destroy
        redirect_to students_path
    end

    def edit 
        @student = Student.find_by(id: params[:id])
    end

    def update
        @student = Student.find_by(id: params[:id])
        if @student.users.include?(current_user)
            @student.update(student_params)
            redirect_to user_students_path(current_user)
        else
            flash[:alert] = "Must be one of your students to edit."
            redirect_to students_path
        end
    end

    private

    def student_params
        params.require(:student).permit(:name, :grade)
    end
end

app/views/students/_form.html.erb
<% if flash.any? %>
    <% flash.each do |type, msg| %>
        <div class="alert alert-danger">
        <%= msg %>
        </div>
    <% end %>
<% end %>

<%= form_with model: @student, local: true do |f| %>
    <% if @student.errors[:name].present? %>
        <%= f.text_field :name, placeholder: "Name #{@student.errors[:name].first}", class: "form-group border border-danger rounded" %>
    <% else %>
        <%= f.text_field :name, placeholder: "Name", class: "form-group border border-secondary rounded" %>
    <% end %>
    <% if @student.errors[:grade].present? %>
        <%= f.text_field :grade, placeholder: "Grade #{@student.errors[:grade].first}", class: "form-group border border-danger rounded" %>
    <% else %>
        <%= f.text_field :grade, placeholder: "Grade: (Enter digit only)", class: "form-group border border-secondary rounded" %>
    <% end %>
  <%= f.submit %>
<% end %>

app/views/students/edit.html.erb
<div class="d-flex  justify-content-center">
    <h3>Edit Student:<h3>
</div>

<div class="d-flex  justify-content-center">
    <%= render 'form' %>
</div>

app/views/students/index.html.erb
 <div class="d-flex justify-content-right">
    <h1><%= current_user.username %>'s students:</h1>
    <ol class="list-group-flush">
    <% @students.each do |s| %>
        <li class="list-group-item"><%= link_to s.name, student_path(s.id) %><br><br>
        <%= link_to "Edit Student", edit_student_path(s) %><br>
        <%= button_to "Delete Student", {controller: :students, action: :destroy, id: s.id}, method: :delete, data: {confirm: "Action cannot be undone, are you sure?"} %><br>
        </li>

    <% end %>
    </ol>
</div>

<div class="d-flex  justify-content-center">
        <%= link_to "back to #{current_user.username}'s Classroom", user_path(current_user) %>
</div>
<div class="d-flex  justify-content-center">
        <%= link_to "Create new course with registered student to add to roster", new_user_course_path(current_user) %>
</div>

app/views/students/new.html.erb
<div class="d-flex  justify-content-center">
    <h1>Create new student:</h1>
</div>

<div class="d-flex  justify-content-center">
    <%= render 'form' %>
</div>

app/views/students/show.html.erb
<div class="container">  
    <div class="d-flex justify-content-center"> 
        <h1><%= @student.name %></h1>
    </div>
    <div class="d-flex justify-content-center"> 
        <h2>Grade: <%= @student.grade %></h2>
    </div>

    <div class="d-flex justify-content-center"> 
        <h3>Courses:</h3>
    </div>
    <div class="d-flex justify-content-center"> 
        <ul class="list-group">
        <% @student.courses.each do |course| %>
            <li class="list-group-item"><%= link_to course.name, course_path(course) %><br><%= course.description %></li>
        <% end %>
        </ul>
    </div>
    
    <div class="d-flex justify-content-center"> 
        <h3>Lessons:</h3> 
    </div>
    <div class="d-flex justify-content-center"> 
        <ul class="list-group">
        <% @student.lessons.each do |lesson| %>
            <li class="list-group-item"><%= link_to lesson.title, lesson_path(lesson) %><br><%= lesson.plan %></li>
        <% end %>
        </ul>
    </div>
</div>