config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  resources :users do
    resources :courses, :students
  end
  resources :students do
    resources :courses
  end
  resources :courses do
    resources :lessons
  end
  resources :lessons
  resources :sessions, only: [:new, :create]
  get 'courses/by_student/:student_id/:user_id', to: 'courses#index'
  get '/signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get 'course/alpha', to: 'courses#alpha'
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :courses
    has_many :students, through: :courses
    has_many :lessons, through: :courses
    validates :username, presence: true
    has_secure_password
    

    def self.from_omniauth(auth)
        where(username: auth.info.first_name).first_or_initialize do |user|
          user.username = auth.info.first_name
          user.password = SecureRandom.hex
        end
    end

    #info=#<OmniAuth::AuthHash::InfoHash
    #  first_name="Google Profile First Name" 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        if session[:user_id]
            redirect_to user_path(current_user)
        else
            @user = User.new
        end
    end

    def index
        if session[:user_id]
            redirect_to user_path(current_user)
        else
            redirect_to root_path
        end
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            flash.now[:alert] = "Username/Password was invalid. Please try again."
            render :new
            # raise @user.errors.inspect
        end
    end
    
    def show
        @user = User.find_by(id: params[:id])
        if @user && @user.id == current_user.id
            @user
        else
            flash[:alert] = "You cannot view other user's classroom"
            redirect_to user_path(current_user)
        end   
        # raise params.inspect
    end

    def destroy
        redirect_to root_path 
    end

    def edit 
        redirect_to root_path
        # @user = User.find_by(id: params[:id]) 
    end

    def update
        redirect_to root_path
        # @user = User.find_by(id: params[:id])
        # if session[:user_id] == @user.id
        #     @user.update(user_params)
        #     redirect_to user_path(@user)
        # else
        #     flash[:alert] = "You can only edit your own information"
        #     redirect_to root_path
        # end 
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

app/views/users/_form.html.erb
    <% if flash.any? %>
    <% flash.each do |type, msg| %>
        <div class="alert alert-danger">
        <%= msg %>
        </div>
    <% end %>
    <% end %>
    
    <%= form_with model: @user, local: true do |f| %>
        <% if @user.errors[:username].present? %>
            <%= f.text_field :username, placeholder: "Name #{@user.errors[:username].first}", class: "form-group border border-danger rounded" %>
        <% else %>
            <%= f.text_field :username, placeholder: "Name", class: "form-group border border-secondary rounded" %>
        <% end %>
        <% if @user.errors[:password].present? %>
            <%= f.password_field :password, placeholder: "Password #{@user.errors[:password].first}", class: "form-group border border-danger rounded" %>
        <% else %>
            <%= f.password_field :password, placeholder: "Password", class: "form-group border border-secondary rounded" %>
        <% end %>
    <%= f.submit %>
    <% end %>

app/views/users/_user_courses.html.erb
<div class="d-flex  justify-content-center">
        <h3>Your Courses:</h3>
    </div>
        <div class="d-flex  justify-content-center">
            <%= link_to "Create new course  ", new_user_course_path(@user) %>
        </div>
        <div class="d-flex  justify-content-center">
            <%= link_to "Edit/Delete Courses", user_courses_path(@user) %>
        </div>
    <div class="d-flex  justify-content-center">
        <ul class="list-group">
        <% @user.courses.each do |course| %>
            <li class="list-group-item"><%= link_to course.name, course_path(course) %><br>
            <%= course.description %><br> Student: <%= course.student.name %><br>
            </li>
        <% end %>
        <br>
        </ul>
    </div>

app/views/users/_user_students.html.erb
    <div class="d-flex  justify-content-center">
        <h3>Your Students:</h3>
    </div>
    <div class="d-flex  justify-content-center">
        <%= link_to "Create New Student", new_student_path %><br>
    </div>
    <div class="d-flex  justify-content-center">
        <%= link_to "Edit/Delete Students", students_path %>
    </div>
    <div class="d-flex  justify-content-center">
        <ul class="list-group">
        <% @user.students.uniq.each do |student| %>
            <li class="list-group-item"><%= link_to student.name, student_path(student) %> <br> Grade: <%= student.grade %></li>
        <% end %>
        </ul>
    </div>

app/views/users/edit.html.erb
<h1>Edit student:</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<div class="container">
  <h1>Sign Up</h1>

  <%= render 'form' %>

  <h2>OR</h2>

  <%= link_to '/auth/google_oauth2', method: :post do %>
      <%= image_tag 'signin_google2.png' %>
  <% end %> 
</div>

app/views/users/show.html.erb
<div class="d-flex  justify-content-center">
    <h1>Hello <%= @user.username %>!</h1>
</div>
<br>
<br>
<br>
<% if flash.any? %>
    <% flash.each do |type, msg| %>
        <div class="d-flex  justify-content-center">
        <div class="alert alert-danger">
        <%= msg %>
        </div>
        </div>
    <% end %>
<% end %>
<div class="container">
        
    <%= render partial: 'users/user_students' %>

    <br>

        <div class="d-flex  justify-content-center">
            <h6>You must <%= link_to "REGISTER STUDENT", new_student_path %> before they can be added to a course. <br> Student must be <%= link_to "enrolled in a course", new_course_path %> to appear in your Student Roster.</h6>
        </div>

    <br>
    
    <%= render partial: 'users/user_courses' %>
</div>