config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  resources :users do
    resources :courses, :students
  end
  resources :students do
    resources :courses
  end
  resources :courses do
    resources :lessons
  end
  resources :lessons
  resources :sessions, only: [:new, :create]
  get 'courses/by_student/:student_id/:user_id', to: 'courses#index'
  get '/signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get 'course/alpha', to: 'courses#alpha'
end

app/models/lesson.rb
class Lesson < ApplicationRecord
    belongs_to :course
    validates :title, presence: true
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
    def index
        if params[:course_id]
            @course = Course.find_by(id: params[:course_id])
            @lessons = @course.lessons
        else
            redirect_to courses_path
        end
    end

    def new
        if params[:course_id] && Course.find_by(id: params[:course_id]).user_id == session[:user_id]
            @lesson = Lesson.new(course_id: params[:course_id])
        else
            redirect_to root_path
        end
    end
    
    def create
        # raise params.inspect
        @lesson = Lesson.new(lesson_params)
        if @lesson.save
            redirect_to course_lesson_path(@lesson.course, @lesson)
        else
            flash.now[:alert]= "Lesson must have title."
            render :new
        end
    end
    
    def show
        @lesson = Lesson.find(params[:id])
    end

    def destroy
        course = Course.find_by(id: params[:course_id])
        lesson = Lesson.find_by(id: params[:id])
        lesson.destroy
        redirect_to course_lessons_path(course)
    end

    def edit 
        @lesson = Lesson.find_by(id: params[:id])
    end

    def update
        @lesson = Lesson.find_by(id: params[:id])
        if session[:user_id] == @lesson.course.user.id
            @lesson.update(lesson_params)
            redirect_to course_lesson_path(@lesson.course, @lesson)
        else
            flash[:alert] = "Lesson must belong to you to edit."
            redirect_to course_lessons_path(@lesson.course)
        end
    end

    private

    def lesson_params
        params.require(:lesson).permit(:title, :plan, :course_id)
    end
end

app/views/lessons/_form.html.erb
<% if flash.any? %>
    <% flash.each do |type, msg| %>
        <div class="alert alert-danger">
        <%= msg %>
        </div>
    <% end %>
<% end %>

<%= form_with model: @lesson, local: true do |f| %>
    <% if @lesson.errors[:title].present? %>
        <h6><%= f.text_field :title, placeholder: "Lesson must have title.", class: "form-group border border-danger rounded" %></h6>
    <% else %>
        <h6><%= f.text_field :title, placeholder: "Give your lesson a title." %></h6>
    <% end %>
    <h6><%= f.text_area :plan, placeholder: "What's the plan" %></h6>
    <%= f.hidden_field :course_id %>
  <%= f.submit %>
<% end %> 

app/views/lessons/edit.html.erb
<div class="d-flex  justify-content-center">
    <h3>Edit Lesson:<h3>
</div>

<div class="d-flex  justify-content-center">
    <%= render 'form' %>
</div>

app/views/lessons/index.html.erb
<div class="d-flex  justify-content-center">
    <h3><%= @course.name %>'s Lessons:</h3>
</div>

<div class="d-flex  justify-content-center">
    <ul class="list-group">
    <% @lessons.each do |lesson| %>
        <li class="list-group-item">
        <%= link_to lesson.title, course_lesson_path(@course, lesson) %><br>
        <%= lesson.plan %><br> Student: <%= lesson.course.student.name %><br>
        <%= link_to "Edit Lesson", edit_course_lesson_path(@course, lesson) %>
        <%= button_to "Delete Lesson", {controller: :lessons, action: :destroy, id: lesson.id}, method: :delete, data: {confirm: "Action cannot be undone, are you sure?"} %>
        <br>
        </li>
    <% end %>
    </ul>
</div>
<br><br><br>
<div class="d-flex  justify-content-center">
        <%= link_to "Create new Lesson", new_course_lesson_path(@course) %>
</div>
<div class="d-flex  justify-content-center">
        <%= link_to "View all courses", user_courses_path(current_user) %>
</div>

app/views/lessons/new.html.erb
<div class="d-flex justify-content-center">  
  <h1>Create a new Lesson</h1>
</div>

<div class="d-flex justify-content-center">  
  <%= render 'form' %>
</div>

<%# <div class="d-flex justify-content-center">  
  <%= link_to "Back to Course", course_path(Course.find_by(id: params[:course_id])) %>

app/views/lessons/show.html.erb
<div class="d-flex  justify-content-center">
    <h1><%= @lesson.title %></h1>
</div>
<div class="d-flex  justify-content-center">    
    <h6><%= @lesson.plan %></h6>
</div>
<div class="d-flex  justify-content-center">    
    <h4>Lesson plan for: <%= @lesson.course.student.name %></h4>
</div>

<div class="d-flex  justify-content-center">    
    <%= link_to "Edit Lesson", edit_course_lesson_path(@lesson.course, @lesson) %>
</div>
<div class="d-flex  justify-content-center">    
    <%= button_to "Delete Lesson", {controller: :lessons, action: :destroy, id: @lesson.id}, method: :delete, data: {confirm: "Action cannot be undone, are you sure?"} %>
</div>
<br><br><br>
<div class="d-flex  justify-content-center">
        <%= link_to "Create new Lesson", new_course_lesson_path(@lesson.course) %>
</div>
<div class="d-flex  justify-content-center">
        <%= link_to "View all lessons for course.", course_lessons_path(@lesson.course) %>
</div>