config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  resources :users do
    resources :courses, :students
  end
  resources :students do
    resources :courses
  end
  resources :courses do
    resources :lessons
  end
  resources :lessons
  resources :sessions, only: [:new, :create]
  get 'courses/by_student/:student_id/:user_id', to: 'courses#index'
  get '/signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get 'course/alpha', to: 'courses#alpha'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    def index
        # raise params.inspect
        if session[:user_id]
            @courses = current_user.courses
            if !params[:student_id].blank?
                @courses = Course.by_student(params[:student_id], params[:user_id])
            end
        else
            flash[:alert] = "Must be logged in to perform this action."
            redirect_to signin_path
        end
    end
    
    def new
        # raise params.inspect
        if session[:user_id]
            @course = Course.new(user_id: session[:user_id]) 
        else
            flash[:alert] = "Must be logged in to create courses."
            redirect_to signin_path
        end
    end
    
    def create 
        @course = Course.new(course_params)
        if @course.save
            redirect_to user_path(@course.user)
        else
            flash.now[:alert] = "Must complete all fields."
            render :new
        end
    end
    
    def show
        @course = Course.find_by(id: params[:id])
        if @course && @course.user.id == current_user.id
            @course
        else
            flash[:alert] = "You cannot view other user's courses"
            redirect_to user_path(current_user)
        end
        # raise params.inspect
    end

    def destroy
        course = Course.find(params[:id])
        course.destroy
        redirect_to user_path(session[:user_id])
    end

    def edit 
        @course = Course.find(params[:id])
    end
    
    def update
        @course = Course.find(params[:id])
        if session[:user_id] == @course.user.id
            @course.update(course_params)
            redirect_to user_courses_path(@course.user)
        else
            flash[:alert] = "Course must belong to you to edit."
            redirect_to courses_path
        end
    end

    def alpha
        @courses = Course.alpha
        render :index
    end

    private

    def course_params
        params.require(:course).permit(:name, :description, :user_id, :student_id)
    end
end

app/views/courses/_form.html.erb
<% if flash.any? %>
    <% flash.each do |type, msg| %>
        <div class="alert alert-danger">
        <%= msg %>
        </div>
    <% end %>
<% end %>

<%= form_with model: @course, local: true do |f| %>
  <% if @course.errors[:name].present? %>
      <h6><%= f.text_field :name, placeholder: "Name #{@course.errors[:name].first}", class: "form-group border border-danger rounded" %></h6>
  <% else %>
      <h6><%= f.text_field :name, placeholder: "Name", class: "form-group border border-secondary rounded" %></h6>
  <% end %>
  <% if @course.errors[:description].present? %>
      <h6><%= f.text_area :description, placeholder: "Description #{@course.errors[:description].first}", class: "form-group border border-danger rounded" %></h6>
  <% else %>
      <h6><%= f.text_area :description, placeholder: "Description", class: "form-group border border-secondary rounded" %></h6>
  <% end %>
    <%= f.label :student_id, "Student must be selected." %>
    <% if @course.student %>
        <h6><%= f.select :student_id, options_from_collection_for_select(Student.all, :id, :name, selected: @course.student.id), include_blank: "Select Student" %></h6>
    <% else %>
        <h6><%= f.select :student_id, options_from_collection_for_select(Student.all, :id, :name), include_blank: "Select Student" %></h6>
    <% end %>
 
    <%= f.hidden_field :user_id %>
  <%= f.submit %>
<% end %>

app/views/courses/_student_li.html.erb
<% student.courses.each do |c| %>
    <% if c.name == @course.name && c.student != @course.student %>
        <li><%= link_to student.name, student_path(student) %><br>Grade: <%= student.grade %></li>
    <% end %>
<% end %>

app/views/courses/alpha.html.erb
<div class="d-flex  justify-content-center">
    <% @courses.each do |c| %>
        <%= c.name %>
    <% end %>
</div>

app/views/courses/edit.html.erb
<div class="container">

    <div class="d-flex  justify-content-center">
    <h3>Edit Course</h3>
    </div>

    <div class="d-flex  justify-content-center">
    <%= render 'form' %>
    </div>
</div>

app/views/courses/index.html.erb
<div class="d-flex  justify-content-center">
    <h1>Your Courses:</h1>
</div>
<div class="d-flex  justify-content-center">
    <%= form_tag("/courses", method: "get") do %>
        <%= select_tag "student_id", options_from_collection_for_select(current_user.students.uniq, :id, :name), include_blank: true %>
        <%= hidden_field_tag "user_id", current_user.id %>
        <%= submit_tag "Filter" %>
    <% end %>
</div>

<div class="d-flex  justify-content-center">
<ul class="list-group">
    <% @courses.each do |course| %>
        <li class="list-group-item">
        <%= link_to course.name, course_path(course) %><br>
        <%= course.description %><br> Student: <%= course.student.name %><br><br>
        <%= link_to "Edit Course", edit_user_course_path(current_user, course) %>
        <%= button_to "Delete Course", {controller: :courses, action: :destroy, id: course.id}, method: :delete, data: {confirm: "Action cannot be undone, are you sure?"} %>
        <br>
        </li>
    <% end %>
</ul>
</div>

<div class="d-flex  justify-content-center">
        <%= link_to "#{current_user.username}'s Classroom", user_path(current_user) %>
</div>

app/views/courses/new.html.erb
  
<div class="container">

  <div class="d-flex  justify-content-center">
    <h1>New Course</h1>
  </div>

  <div class="d-flex  justify-content-center">
    <%= render 'form' %>
  </div>

  <div class="d-flex  justify-content-center">
    <%= link_to "Need to register a new student?", new_student_path %>
  </div>

</div>

app/views/courses/show.html.erb
<div class="container">
    <div class="d-flex  justify-content-center">
    <h1><%= @course.name %></h1>
    </div>

    <div class="d-flex  justify-content-center">
    <h5 class="text-center"><%= @course.description %></h5>
    </div>
    <div class="d-flex  justify-content-center">
    <p>fine tuned for: <%= @course.student.name %></p>
    </div>

    <div class="d-flex  justify-content-center">
    <h3>Lessons:</h3>
    </div>
    <div class="d-flex  justify-content-center">
        <%= link_to "Create new Lesson", new_course_lesson_path(@course) %>
    </div>
    <div class="d-flex  justify-content-center">
        <%= link_to "Edit/Delete Lessons", course_lessons_path(@course) %>
    </div>
    <div class="d-flex  justify-content-center">
    <ul class="list-group">
    <% @course.lessons.each do |lesson| %>
        <li class="list-group-item"><%= link_to lesson.title, lesson_path(lesson) %><br><%= lesson.plan %></li>
    <% end %>
    </ul>
    </div>

    <div class="d-flex  justify-content-center">
    <h3>Other Students Taking this Course:</h3>
    </div>

    <div class="d-flex  justify-content-center">
    <ol>
    <% Student.all.each do |student| %>
        <%= render partial: "courses/student_li", locals: {student: student} %>
    <% end %>
    </ol>
    </div>
</div>